INSERT INTO "Subareas" (descripcion, "creationDate", "updatedOn", "areaId")
VALUES ('Visión Computacional', NOW(), NOW(), 1),
('Procesamiento de Lenguaje Natural', NOW(), NOW(), 1),
('Aprendizaje Automático', NOW(), NOW(), 1),
('Minería de Datos', NOW(), NOW(), 1),
('Seguridad de Sistemas y Aplicaciones', NOW(), NOW(), 2),
('IoT', NOW(), NOW(), 2),
('Computación de alto rendimiento', NOW(), NOW(), 2),
('Redes y ciberseguridad', NOW(), NOW(), 2),
('Sostenibilidad en TI', NOW(), NOW(), 2),
('HCI (Interacción Humano-Computadora)', NOW(), NOW(), 3),
('Realidad Virtual y Aumentada (RV/RA)', NOW(), NOW(), 3),
('Construcción de Juegos y Gamificación', NOW(), NOW(), 3),
('Agentes virtuales', NOW(), NOW(), 3),
('Optimización computacional', NOW(), NOW(), 4),
('Ingenieria de software', NOW(), NOW(), 4),
('Diseño de algoritmos', NOW(), NOW(), 4),
('Gestión de procesos tecnológicos', NOW(), NOW(), 5),
('Tecnología y gestión de proyectos', NOW(), NOW(), 5),
('Liderazgo, género y tecnología', NOW(), NOW(), 5),
('Sistemas de gestión del conocimiento', NOW(), NOW(), 5),
('Minería de procesos', NOW(), NOW(), 5),
('Computación Aplicada', NOW(), NOW(), 5),
('Simulación de procesos', NOW(), NOW(), 5);
